### ISSUE TITLE
Flippable crashes when attempting to flip the card.

### ISSUE THREAD

**Issue by stevetripp** [wajahatkarim3/Flippable#14]
Compose Version = 1.5.7
Kotlin Version = 1.9.21
agpVersion = 8.2.0
Gradle wrapper = 8.5

java.lang.NoSuchMethodError: No virtual method at(Ljava/lang/Object;I)Landroidx/compose/animation/core/KeyframesSpec$KeyframeEntity; in class Landroidx/compose/animation/core/KeyframesSpec$KeyframesSpecConfig; or its super classes (declaration of 'androidx.compose.animation.core.KeyframesSpec$KeyframesSpecConfig')
                                                                	at com.wajahatkarim.flippable.FlippableKt$Flippable$frontRotation$2$1.invoke(Flippable.kt:167)
                                                                	at com.wajahatkarim.flippable.FlippableKt$Flippable$frontRotation$2$1.invoke(Flippable.kt:165)
                                                                	at androidx.compose.animation.core.AnimationSpecKt.keyframes(AnimationSpec.kt:649)
                                                                	at com.wajahatkarim.flippable.FlippableKt$Flippable$frontRotation$2.invoke(Flippable.kt:165)
                                                                	at com.wajahatkarim.flippable.FlippableKt$Flippable$frontRotation$2.invoke(Flippable.kt:161)
                                                                	at com.wajahatkarim.flippable.FlippableKt.Flippable(Flippable.kt:372)
                                                                	at com.wajahatkarim.flippable.FlippableKt$Flippable$7.invoke(Unknown Source:46)
                                                                	at com.wajahatkarim.flippable.FlippableKt$Flippable$7.invoke(Unknown Source:10)
                                                                	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
                                                                	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2556)
                                                                	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2827)
                                                                	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3314)
                                                                	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3265)
                                                                	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:938)
                                                                	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1155)
                                                                	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:127)
                                                                	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:583)
                                                                	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
                                                                	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
                                                                	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
                                                                	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
                                                                	at android.view.Choreographer.doFrame(Choreographer.java:878)
                                                                	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
                                                                	at android.os.Handler.handleCallback(Handler.java:958)
                                                                	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                	at android.os.Looper.loopOnce(Looper.java:205)
                                                                	at android.os.Looper.loop(Looper.java:294)
                                                                	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                	at java.lang.reflect.Method.invoke(Native Method)
                                                                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrame

**Comment by joyner-perez** [comment]
In my case this error occurred when update the compose bom from version 2023.10.01 to 2024.01.00. I trying to reproduce the error after upgraded this project but don't occurred, I hope helped you

**Comment by PatrickKuijpers** [comment]
Same issue here, also caused by the same compose bom update as [joyner-perez](https://github.com/joyner-perez)

**Comment by joyner-perez** [comment]
Yesterday, Google released a new version but I haven't been able to test it yet

**Comment by joyner-perez** [comment]
With the last version of compose bom: 2024.02.00 the problem has solved
